// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU8f-J4UsapcvfLaHa9BYqtwtB9DcBdB0',
    appId: '1:666516149325:web:c0c52fe51d992c2aad7804',
    messagingSenderId: '666516149325',
    projectId: 'sycx-e17d1',
    authDomain: 'sycx-e17d1.firebaseapp.com',
    storageBucket: 'sycx-e17d1.appspot.com',
    measurementId: 'G-7WTQ4BBGVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hgxRTYfp1Bh7-AqXsbGEHvEVz8hIFiQ',
    appId: '1:666516149325:android:f3b9aed644e760f3ad7804',
    messagingSenderId: '666516149325',
    projectId: 'sycx-e17d1',
    storageBucket: 'sycx-e17d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZn-9L0G3cEk3dEO1VSEMnZIfxm0byTFs',
    appId: '1:666516149325:ios:dbdbccceabe374adad7804',
    messagingSenderId: '666516149325',
    projectId: 'sycx-e17d1',
    storageBucket: 'sycx-e17d1.appspot.com',
    androidClientId: '666516149325-qdr2e27nkbhviiul07be9poj5hq22u16.apps.googleusercontent.com',
    iosClientId: '666516149325-qbtd9b7gpa2oa80ojipg5b5i67492hgk.apps.googleusercontent.com',
    iosBundleId: 'com.donartkins.sycx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZn-9L0G3cEk3dEO1VSEMnZIfxm0byTFs',
    appId: '1:666516149325:ios:dbdbccceabe374adad7804',
    messagingSenderId: '666516149325',
    projectId: 'sycx-e17d1',
    storageBucket: 'sycx-e17d1.appspot.com',
    androidClientId: '666516149325-qdr2e27nkbhviiul07be9poj5hq22u16.apps.googleusercontent.com',
    iosClientId: '666516149325-qbtd9b7gpa2oa80ojipg5b5i67492hgk.apps.googleusercontent.com',
    iosBundleId: 'com.donartkins.sycx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU8f-J4UsapcvfLaHa9BYqtwtB9DcBdB0',
    appId: '1:666516149325:web:02559786c791abb9ad7804',
    messagingSenderId: '666516149325',
    projectId: 'sycx-e17d1',
    authDomain: 'sycx-e17d1.firebaseapp.com',
    storageBucket: 'sycx-e17d1.appspot.com',
    measurementId: 'G-53QR60FW4J',
  );

}